### ISSUE TITLE
Error when executing plugin

### ISSUE THREAD

**Issue by felipecorrea9** [TheDevFreak/plugin.video.f1tv#1]
Hi,
Im getting an error when trying to open the plugin.
Any ideas?

```
File "/storage/.kodi/addons/plugin.video.f1tv/main.py", line 14, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 550, in run
                                                apikey, system_id = _api_manager.account_manager.exteractSessionData()
                                              File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/F1TVParser/AccountManager.py", line 34, in exteractSessionData
                                                return self.auth_headers['apikey'], self.auth_headers['cd-systemid']
                                            KeyError: 'apikey'
                                            -->End of Python script error report<--
2020-01-23 01:46:05.398 T:1551049584   ERROR: GetDirectory - Error getting plugin://plugin.video.f1tv/
2020-01-23 01:46:05.402 T:1937369488   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/) failed
```

**Comment by devil-strike** [comment]
Got the same error on on the Shield 
`2020-02-05 20:19:36.373 T:25239   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'apikey'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.f1tv/main.py", line 14, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 550, in run
                                                apikey, system_id = _api_manager.account_manager.exteractSessionData()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.f1tv/resources/lib/F1TVParser/AccountManager.py", line 34, in exteractSessionData
                                                return self.auth_headers['apikey'], self.auth_headers['cd-systemid']
                                            KeyError: 'apikey'
                                            -->End of Python script error report<--
2020-02-05 20:19:36.434 T:25237   ERROR: GetDirectory - Error getting plugin://plugin.video.f1tv/
2020-02-05 20:19:36.436 T:21990   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/) failed`

**Comment by pogo1975** [comment]
you are not alone in Windows:
 ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.f1tv/
2020-02-08 18:06:58.383 T:16792   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/) failed
2020-02-08 18:06:59.859 T:15952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'apikey'
                                            Traceback (most recent call last):
                                              File "C:\Users\Jarek\AppData\Roaming\Kodi\addons\plugin.video.f1tv\main.py", line 14, in <module>
                                                plugin.run()
                                              File "C:\Users\Jarek\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\plugin.py", line 550, in run
                                                apikey, system_id = _api_manager.account_manager.exteractSessionData()
                                              File "C:\Users\Jarek\AppData\Roaming\Kodi\addons\plugin.video.f1tv\resources\lib\F1TVParser\AccountManager.py", line 34, in exteractSessionData
                                                return self.auth_headers['apikey'], self.auth_headers['cd-systemid']
                                            KeyError: 'apikey'
                                            -->End of Python script error report<--

**Comment by RogerKrowiak** [comment]
I have another issue with this plugin. I have valid account, I can use it with browser. I've successfully installed the plugin into Kodi 18.9 on LibreELEC 9.2.6. I've entered the credentials, but the plugin fails to start with following error in log:

```
ERROR: sk
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
      - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
     Error Type: <type 'exceptions.IndexError'>
     Error Contents: list index out of range
     Traceback (most recent call last):
       File "/storage/.kodi/addons/plugin.video.f1tv/main.py", line 14, in <module>
         plugin.run()
       File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 530, in run
         router(sys.argv[2][1:])
       File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 504, in router
         get_mainpage()
       File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 41, in get_mainpage
         event_uid = _api_manager.getLiveEvent()
       File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/F1TVParser/F1TV_Minimal_API.py", line 138, in getLiveEvent
         return element['content_url']['items'][0]['content_url']['uid']
     IndexError: list index out of range
     -->End of Python script error report<--
ERROR: GetDirectory - Error getting plugin://plugin.video.f1tv/
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/) failed
```

Any idea how can I fix this? Thank you for your reply.

**Comment by Mikelarrr** [comment]
> I have another issue with this plugin. I have valid account, I can use it with browser. I've successfully installed the plugin into Kodi 18.9 on LibreELEC 9.2.6. I've entered the credentials, but the plugin fails to start with following error in log:
> 
> ```
> ERROR: sk
> ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>       - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>      Error Type: <type 'exceptions.IndexError'>
>      Error Contents: list index out of range
>      Traceback (most recent call last):
>        File "/storage/.kodi/addons/plugin.video.f1tv/main.py", line 14, in <module>
>          plugin.run()
>        File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 530, in run
>          router(sys.argv[2][1:])
>        File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 504, in router
>          get_mainpage()
>        File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/plugin.py", line 41, in get_mainpage
>          event_uid = _api_manager.getLiveEvent()
>        File "/storage/.kodi/addons/plugin.video.f1tv/resources/lib/F1TVParser/F1TV_Minimal_API.py", line 138, in getLiveEvent
>          return element['content_url']['items'][0]['content_url']['uid']
>      IndexError: list index out of range
>      -->End of Python script error report<--
> ERROR: GetDirectory - Error getting plugin://plugin.video.f1tv/
> ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.f1tv/) failed
> ```
> 
> Any idea how can I fix this? Thank you for your reply.

I had the same issue, I noticed the lines referenced in the error messages were actually referring to objects in the old version of the plugin (which I updated from). After deleting the addon and re-installing, I'm now getting the same 'API' errors as the other posters.

Looking through bbsan2k's git issues here, https://github.com/bbsan2k/plugin.video.f1tv/issues/44, it looks like it's an issue of Kodi 18.x not supporting F1TV's new API:

"The problem with supporting Leia (18.x) is, that due to the changes in F1TVs API, the player in Leia is not able to correctly parse the live stream m3u8. The addon itself does not have any dependencies for Matrix."

There's a new version of the original plugin for Kodi 19 Matrix, so I guess that's the solution.
https://github.com/bbsan2k/plugin.video.f1tv/releases/tag/0.1.100
